version: '3'
services:
  penr-oz-spring-aws-redis:
    image: openjdk:11-jre-slim
    container_name: penr-oz-spring-aws-redis
    volumes:
    - ./build/libs/penr-oz-spring-aws-redis-0.0.1.jar:/app.jar
    entrypoint: java
    command: -jar /app.jar
    ports:
    - "8080:8080"
    depends_on:
      - localstack
      - redis
    environment:
      AWS_SERVICE_ENDPOINT: http://localstack:4566
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: test
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: test
      CLOUD_AWS_INSTANCE_DATA_ENABLED: "false"
      CLOUD_AWS_INSTANCE_PROFILE: "false"
      CLOUD_AWS_REGION_AUTO: "false"
      CLOUD_AWS_REGION_STATIC: us-east-1
      CLOUD_AWS_STACK_AUTO: "false"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  localstack:
    image: localstack/localstack:0.12.19.1
    container_name: localstack
    environment:
      SERVICES: ec2,ec2-instance-connect,iam

  redis:
    image: redis:6.2.6-alpine
    container_name: redis